### ISSUE TITLE
Error when deleting a monograph

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1024]
I'm getting an error when I try to delete a monograph in the UI. The error prevents the monograph from being deleted. Possibly related to #1016?

Update: This might be related to my dev environment only (there's a lot of chrun going on..). Please close this if it can't be reproduced.

```
Completed 500 Internal Server Error in 96ms (ActiveRecord: 1.8ms)


  
NoMethodError (undefined method `build' for nil:NilClass):
  
.bundle/ruby/2.3.0/gems/hyrax-1.0.1/app/services/hyrax/curation_concern.rb:13:in `actor'
.bundle/ruby/2.3.0/gems/hyrax-1.0.1/app/controllers/concerns/hyrax/curation_concern_controller.rb:125:in `actor'
.bundle/ruby/2.3.0/gems/hyrax-1.0.1/app/controllers/concerns/hyrax/curation_concern_controller.rb:102:in `destroy'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/abstract_controller/base.rb:188:in `process_action'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:126:in `call'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `block in instrument'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `instrument'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
.bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/abstract_controller/base.rb:126:in `process'
.bundle/ruby/2.3.0/gems/actionview-5.0.2/lib/action_view/rendering.rb:30:in `process'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_controller/metal.rb:190:in `dispatch'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_controller/metal.rb:262:in `dispatch'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:32:in `serve'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:39:in `block in serve'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:26:in `each'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/journey/router.rb:26:in `serve'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:725:in `call'
.bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
.bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
.bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
.bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
.bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
.bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
.bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
.bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
.bundle/ruby/2.3.0/gems/active-fedora-11.1.6/lib/active_fedora/ldp_cache.rb:26:in `call'
.bundle/ruby/2.3.0/gems/flipflop-2.3.1/lib/flipflop/feature_cache.rb:12:in `call'
.bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:553:in `call'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
.bundle/ruby/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
.bundle/ruby/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
.bundle/ruby/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
.bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:36:in `call_app'
.bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `block in call'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26:in `tagged'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `tagged'
.bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `call'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
.bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
.bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
.bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
.bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/static.rb:136:in `call'
.bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
.bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:522:in `call'
.bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
.bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
.bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
.bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
.bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by gkostin1966** [comment]
Ldp::Gone in Hyrax::MonographsController#destroy
Extracted source (around line #119):
117
118
119
120
121
122
              
    resp.tap do |resp|
      unless resp.status < 400
        raise case resp.status
          when 400
            if resp.env.method == :head
              # If the request was a HEAD request (which only retrieves HTTP headers),

Rails.root: /Users/gkostin/github/mlibrary/heliotrope

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"_method"=>"delete", "authenticity_token"=>"H+lkocZUJCqaWmwYXEwtrbYIfo3TZ1zOi+rUqcCnKS8fXxZzWIOYGFRqoVfRGZFXEgOI1dwDLMMdJticx1PRZA==", "locale"=>"en", "id"=>"n009w228g"}
Toggle session dump
Toggle env dump
Response

Headers:

None

**Comment by gkostin1966** [comment]
module Hyrax
  module WorksControllerBehavior
    extend ActiveSupport::Concern
    # TODO: merge with CurationConcernController
    include Hyrax::CurationConcernController
