### ISSUE TITLE
Can't find user "system" in production

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1408]
In production, when a platform_admin is in the dashboard and clicks on "Reports" they get a 500 error. In the logs there's this:

```
I, [2017-12-07T09:47:56.575471 #37272]  INFO -- : [a0e21ce0-89b1-40b6-b83f-707ed27e2507]   Rendered /hydra/heliotrope-production/shared/vendor/bundle/ruby/2.4.0/gems/hyrax-2.0.0/app/views/hyrax/admin/stats/_deposits.html.erb (12.9ms)
I, [2017-12-07T09:47:56.575587 #37272]  INFO -- : [a0e21ce0-89b1-40b6-b83f-707ed27e2507]   Rendered /hydra/heliotrope-production/shared/vendor/bundle/ruby/2.4.0/gems/hyrax-2.0.0/app/views/hyrax/admin/stats/_stats_by_date.html.erb (50.7ms)
I, [2017-12-07T09:47:56.575659 #37272]  INFO -- : [a0e21ce0-89b1-40b6-b83f-707ed27e2507]   Rendered /hydra/heliotrope-production/shared/vendor/bundle/ruby/2.4.0/gems/hyrax-2.0.0/app/views/hyrax/admin/stats/show.html.erb within layouts/dashboard (56.2ms)
I, [2017-12-07T09:47:56.575894 #37272]  INFO -- : [a0e21ce0-89b1-40b6-b83f-707ed27e2507] Completed 500 Internal Server Error in 98ms (ActiveRecord: 7.1ms)
F, [2017-12-07T09:47:56.578074 #37272] FATAL -- : [a0e21ce0-89b1-40b6-b83f-707ed27e2507]   
F, [2017-12-07T09:47:56.578115 #37272] FATAL -- : [a0e21ce0-89b1-40b6-b83f-707ed27e2507] ActionView::Template::Error (Unable to find user 'system'
F, [2017-12-07T09:47:56.578227 #37272] FATAL -- : [a0e21ce0-89b1-40b6-b83f-707ed27e2507]     1: <h3>Deposits By Users (<%= @presenter.date_filter_string %>)</h3>
[a0e21ce0-89b1-40b6-b83f-707ed27e2507]     2: <ul>
[a0e21ce0-89b1-40b6-b83f-707ed27e2507]     3:   <% @presenter.depositors.each do |usr| %>
[a0e21ce0-89b1-40b6-b83f-707ed27e2507]     4:     <li>
[a0e21ce0-89b1-40b6-b83f-707ed27e2507]     5:       <%= link_to usr[:user].name, hyrax.user_path(usr[:user]), title: "View user's profile" %>
[a0e21ce0-89b1-40b6-b83f-707ed27e2507]     6:       deposited <%= pluralize(usr[:deposits], "file") %>
F, [2017-12-07T09:47:56.578264 #37272] FATAL -- : [a0e21ce0-89b1-40b6-b83f-707ed27e2507]   
F, [2017-12-07T09:47:56.578320 #37272] FATAL -- : [a0e21ce0-89b1-40b6-b83f-707ed27e2507] hyrax (2.0.0) app/services/hyrax/statistics/depositors/summary.rb:29:in `block in depositors'
[a0e21ce0-89b1-40b6-b83f-707ed27e2507] hyrax (2.0.0) app/services/hyrax/statistics/depositors/summary.rb:27:in `each'
[a0e21ce0-89b1-40b6-b83f-707ed27e2507] hyrax (2.0.0) app/services/hyrax/statistics/depositors/summary.rb:27:in `each_slice'
[a0e21ce0-89b1-40b6-b83f-707ed27e2507] hyrax (2.0.0) app/services/hyrax/statistics/depositors/summary.rb:27:in `each'
[a0e21ce0-89b1-40b6-b83f-707ed27e2507] hyrax (2.0.0) app/services/hyrax/statistics/depositors/summary.rb:27:in `map'
[a0e21ce0-89b1-40b6-b83f-707ed27e2507] hyrax (2.0.0) app/services/hyrax/statistics/depositors/summary.rb:27:in `depositors'
[a0e21ce0-89b1-40b6-b83f-707ed27e2507] hyrax (2.0.0) app/services/hyrax/statistics/depositors/summary.rb:13:in `depositors'
[a0e21ce0-89b1-40b6-b83f-707ed27e2507] hyrax (2.0.0) app/presenters/hyrax/admin_stats_presenter.rb:29:in `depositors'
...
```

I suspect that we're seeing this in production (and not staging/preview/testing) because the importer used to use the fake user "system" when adding a monograph, but Hyrax doesn't like that (the importer now requires the email address of the person running it to be the "depositor").

We'll probably need to change the "depositor" of all the mongraphs in production to be an actual user. I'm pretty sure you can't do this in the UI, so we'll probably have to do it via the console.

**Comment by conorom** [comment]
Replicated the 500 error in dev by setting the depositor to the non-existent 'system' user. Then set it back to my email and all was fine.

Decided to do the same on production. I also conditionally set the depositor on FileSets, which took a really long time to run. I think we have about 1000 FileSets now. I should have used `screen` as I was nervous the VPN/ssh session would randomly die before the thing finished (though presumably that wouldn't break everything, it's not something I'd like to see happen). Also a print out of progress would have been comforting. Maybe I'll remember to do this stuff next time.

```
Monograph.all.to_a.each{ |m| if m.depositor == 'system' then  m.depositor = '[Conor's email address]'; m.save! end } ;0
FileSet.all.to_a.each{ |f| if f.depositor == 'system' then  f.depositor = '[Conor's email address]'; f.save! end } ;0
```
