### ISSUE TITLE
Visibility isn't being set right when uploading a file

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#272]
* Go to a Monograph or Section
* Click "Attach a File" (not the green "+Select Files" button)
* Choose any Visibility
* Click "Attach to Monograph|Section"
* Navigate back to the File and click "Edit File"

A Lease is always set? I'm not sure if this is correct/right or not. Need to investigate.

**Comment by sethaj** [comment]
I might be that these are just coming in from the form on POST and should be filtered out (if a lease or embargo is not explicitly set)

```
Started POST "/concern/container/6t053f984/file_sets" for 127.0.0.1 at 2016-06-24 14:01:51 -0400
Processing by CurationConcerns::FileSetsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"q0GtW0SBYFvAS+g38Zm7gc7EENQ1SfSbhSXBHcVTuOFQskW8z5ankpLCOq5pAjLk+EGQBQQga3Vn8eFaPv30vQ==", "file_set"=>{"title"=>["Acting"], "files"=>[#<ActionDispatch::Http::UploadedFile:0x007fd9e9af2f60 @tempfile=#<Tempfile:/tmp/RackMultipart20160624-17897-1qh133e.gif>, @original_filename="riker_acting.gif", @content_type="image/gif", @headers="Content-Disposition: form-data; name=\"file_set[files][]\"; filename=\"riker_acting.gif\"\r\nContent-Type: image/gif\r\n">], "resource_type"=>[""], "caption"=>[""], "alt_text"=>[""], "copyright_holder"=>[""], "description"=>["I think you've let your personal feelings cloud your judgement."], "content_type"=>[""], "creator_family_name"=>"", "creator_given_name"=>"", "contributor"=>[""], "date_created"=>[""], "keywords"=>[""], "language"=>[""], "identifier"=>[""], "relation"=>[""], "external_resource"=>[""], "persistent_id"=>[""], "visibility"=>"open", "visibility_during_embargo"=>"restricted", "embargo_release_date"=>"2016-06-25", "visibility_after_embargo"=>"open", "visibility_during_lease"=>"open", "lease_expiration_date"=>"2016-06-25", "visibility_after_lease"=>"restricted"}, "commit"=>"Attach to Section", "parent_id"=>"6t053f984"}
```

**Comment by sethaj** [comment]
Can't set Lease to a FileSet:

* Create a monograph in the usual way
* On the monograph show page, click "Attach A File"
* Give it a title, pick visibility "Lease" and accept the defaults
* Click "Attach to Monograph"

```
ArgumentError in CurationConcerns::FileSetsController#create
Invalid visibility: "lease"

Extracted source (around line #16):

        private_visibility!
      else
16:        raise ArgumentError, "Invalid visibility: #{value.inspect}"
      end
    end


Rails.root: /home/seth/apps/heliotrope

Application Trace | Framework Trace | Full Trace
.bundle/ruby/2.2.0/gems/hydra-access-controls-9.9.0/app/models/concerns/hydra/access_controls/visibility.rb:16:in `visibility='
.bundle/ruby/2.2.0/gems/hydra-access-controls-9.9.0/app/models/concerns/hydra/access_controls/embargoable.rb:66:in `visibility='
.bundle/ruby/2.2.0/gems/active-fedora-9.10.4/lib/active_fedora/attribute_assignment.rb:52:in `public_send'
...

```

**Comment by sethaj** [comment]
Same with Embargo. Choosing "Embargo" you get the error:

```
Invalid visibility: "embargo"
```

**Comment by sethaj** [comment]
Possibly related:

https://groups.google.com/forum/#!searchin/hydra-tech/visibility/hydra-tech/bEjUiLS6HiU/uWvi9ssVAQAJ

But I don't think we'll take this approach *right now*.

https://github.com/ualbertalib/sufia/commit/4edf55214f7064e8a4aec7290f4f1b30a60571d8

As long as the Importer is fine (and should be since it only uses Actors).
