### ISSUE TITLE
IO error bug

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#416]
Need to fix a bug in Riiif::File that causes this error:

```
D, [2016-08-19T15:13:27.431675 #20615] DEBUG -- :   Load LDP (164.1ms) http://localhost:8080/fedora/rest/heliotrope-staging/0r/96/73/74/0r967374w Service: 70016893244600
I, [2016-08-19T15:13:27.543019 #20615]  INFO -- : Completed 500 Internal Server Error in 507ms (ActiveRecord: 0.0ms)
F, [2016-08-19T15:13:27.546274 #20615] FATAL -- : 
IOError (closed stream):
  app/models/riiif/file.rb:37:in `extract'
```

It happens every so often in staging with the effect that one of the tiles of an image in Leaflet will be missing.

Probably just need to close the IO object after reading (oops) like: 

https://github.com/albertbellonch/piet/commit/0ec7b3ddc3d34ff16da887570d54f429a8df7eb4

**Comment by sethaj** [comment]
PR #417 didn't quite fix this, it's still an issue (in staging)

```
E, [2016-08-19T16:41:59.848150 #32510] ERROR -- : Could not log "process_action.action_controller" event. RuntimeError: can't modify frozen IOError ["/l/local/rbenv/versions/2.3.0/lib/ruby/2.3.0/logger.rb:660:in `write'", "/l/local/rbenv/versions/2.3.0/lib/ruby/2.3.0/logger.rb:660:in `warn'", "/l/local/rbenv/versions/2.3.0/lib/ruby/2.3.0/logger.rb:660:in `rescue in write'", "/l/local/rbenv/versions/2.3.0/lib/ruby/2.3.0/logger.rb:644:in `write'", "/l/local/rbenv/versions/2.3.0/lib/ruby/2.3.0/logger.rb:433:in `add'", "/hydra-dev/heliotrope-staging/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/logger.rb:52:in `add'", "/l/local/rbenv/versions/2.3.0/lib/ruby/2.3.0/logger.rb:489:in `info'", "/hydra-dev/heliotrope-staging/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/log_subscriber.rb:93:in `info'", "/hydra-dev/heliotrope-staging/shared/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/log_subscriber.rb:18:in `process_action'", "/hydra-dev/heliotrope-staging/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/subscriber.rb:100:in `finish'", "/hydra-dev/heliotrope-staging/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/log_subscriber.rb:83:in `finish'", "/hydra-dev/heliotrope-staging/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb:102:in `finish'", "/hydra-dev/heliotrope-staging/shared/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb:46:in `block in finish'", "/hydra-dev/heliotr
...
```
