### ISSUE TITLE
error on "Lateen Sail Design"

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#533]
File name is `Sails_1.tif`

tifftopnm, which is employed by Leaflet, can't handle a value on this tiff, such that nothing is shown in the Leaflet image area

production error:
```
I, [2016-10-17T10:59:09.578797 #29026]  INFO -- : Completed 500 Internal Server Error in 247ms (ActiveRecord: 0.0ms)
F, [2016-10-17T10:59:09.580756 #29026] FATAL -- :
RuntimeError (Unable to execute command "tifftopnm -byrow tmp/network_files/c1b40e2768c8534c679a590ec003cb93 | pamcut 0 0 2048 2048 | pnmscalefixed -xsize 256 | pnmtojpeg -quality 95"
TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
tifftopnm: don't know how to handle PHOTOMETRIC_YCBCR
pamcut: Error reading magic number from Netpbm image stream.  Most often, this means your input file is empty.
pnmscalefixed: Error reading magic number from Netpbm image stream.  Most often, this means your input file is empty.
pnmtojpeg: Error reading magic number from Netpbm image stream.  Most often, this means your input file is empty.
):
  app/models/riiif/file.rb:101:in `block in execute'
  app/models/riiif/file.rb:93:in `execute'
  app/models/riiif/file.rb:43:in `extract'
```

**Comment by conorom** [comment]
I think this may be a case where we change the image. Bug reports relating to this all seem extremely old, so I guess this is not getting fixed any time soon.

Googling `tifftopnm  "PHOTOMETRIC_YCBCR"` this will get you the really old bug reports and the tifftopnm code that spits out the error (from netpbm 9.25, but whatever).

nectar exhibits this issue. Both it and bulleit-1 have netpbm 10.47.62 
I think we can expect to be stuck with this one.

**Comment by conorom** [comment]
Recreating the tiff seems to have worked on staging. Closing this.
