### ISSUE TITLE
Update to CC 1.7.0

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#676]
Or maybe wait until 2.0 (rc1 is out now).

**Comment by sethaj** [comment]
Today (yesterday?) CC 1.7.0 was given the "latest release" flag (was 1.6.3).

I was on the fence about this upgrade. It provides workflows via sipity which can be very complex and the changes introduced a lot of code. But at the same time possibly isn't really "done" enough for usto take advantage of as it currently exists in 1.7.0. For instance in Hyrax (which is at version 0.0.1ish) workflows can be changed and assigned based on administrative sets and there's a notification mechanism.   But it seems that in CC right now there's limited support for admin_sets, so no real place to "hang" a workflow. There doesn't seem to be a UI for creating admin_sets. Notifications don't seem to be there yet either.

Another feature is the administrative dashboard (/admin). Like workflows I think there's a lot of promise here, but I'm not sure it realized yet, or is something we're ready to really get into.

The current/default workflow that ships with 1.7.0 is sort of a "no" workflow, so we could do this update and it would be fine. We can ignore the admin dashboard until we're ready to work on it.

Originally I wasn't going to bother with the upgrade, but since 1.7.0 is now the "latest release" I think we should do it. Even if we don't use the features we should try to stay current as we look toward the long term goal of (probably!) migrating from CC to Hyrax.

**Comment by sethaj** [comment]
There are migrations, so developers will need to
`rake db:migrate`

and then also load the default workflow which is:

`rake curation_concerns:workflow:load`

**Comment by sethaj** [comment]
If a work was created before the introduction of CC 1.7.0 with sipity workflows, apparently this error can happen:

```
I, [2017-01-27T14:02:48.047912 #23564]  INFO -- : Started GET "/concern/monographs/zs25x856m/show" for 141.211.43.239 at 2017-01-27 14:02:48 -0500

...

D, [2017-01-27T14:02:48.083821 #23564] DEBUG -- :   Sipity::Entity Load (0.4ms)  SELECT  `sipity_entities`.* FROM `sipity_entities` WHERE `sipity_entities`.`proxy_for_global_id` = 'gid://heliotrope/Monograph/zs25x856m' LIMIT 1
I, [2017-01-27T14:02:48.085186 #23564]  INFO -- : Completed 500 Internal Server Error in 30ms (ActiveRecord: 2.6ms)
F, [2017-01-27T14:02:48.089367 #23564] FATAL -- : 
PowerConverter::ConversionError (Unable to convert #<URI::GID gid://heliotrope/Monograph/zs25x856m> to 'sipity_entity' (scope: nil).):
  power_converter (0.1.2) lib/power_converter.rb:162:in `convert'
  power_converter (0.1.2) lib/power_converter.rb:259:in `method_missing'
  curation_concerns (1.7.0) app/conversions/power_converters/sipity_entity.rb:6:in `block in <top (required)>'

...
```

I thought this was working/fixed, but it's not. Need to figure out a data migration path maybe.
