### ISSUE TITLE
UI: changing a fileset's title in the section file manager fails

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#702]
log output:

```
I, [2017-01-18T15:33:11.178883 #6548]  INFO -- : Completed 500 Internal Server Error in 2766ms (ActiveRecord: 22.6ms)
F, [2017-01-18T15:33:11.181330 #6548] FATAL -- :
ActionView::Template::Error (undefined method `label' for #<CurationConcerns::FileSetPresenter:0x007fe2a2a5b158>):
    1: json.extract! @presenter, :id, :title, :label, :description, :creator
  jbuilder (2.5.0) lib/jbuilder.rb:260:in `public_send'
  jbuilder (2.5.0) lib/jbuilder.rb:260:in `block in _extract_method_values'
  jbuilder (2.5.0) lib/jbuilder.rb:260:in `each'
  jbuilder (2.5.0) lib/jbuilder.rb:260:in `_extract_method_values'
  jbuilder (2.5.0) lib/jbuilder.rb:219:in `extract!'
  curation_concerns (1.6.2) app/views/curation_concerns/file_sets/show.json.jbuilder:1:in `__hydra_dev_heliotrope_staging_shared_vendor_bundle_ruby_______gems_curation_concerns_______app_views_curation_concerns_file_sets_show_json_jbuilder___2034905076601711768_70305683846280'
  actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
```

**Comment by conorom** [comment]
```
I, [2017-01-18T15:33:11.178883 #6548]  INFO -- : Completed 500 Internal Server Error in 2766ms (ActiveRecord: 22.6ms)
F, [2017-01-18T15:33:11.181330 #6548] FATAL -- :
ActionView::Template::Error (undefined method `label' for #<CurationConcerns::FileSetPresenter:0x007fe2a2a5b158>):
    1: json.extract! @presenter, :id, :title, :label, :description, :creator
  jbuilder (2.5.0) lib/jbuilder.rb:260:in `public_send'
  jbuilder (2.5.0) lib/jbuilder.rb:260:in `block in _extract_method_values'
  jbuilder (2.5.0) lib/jbuilder.rb:260:in `each'
  jbuilder (2.5.0) lib/jbuilder.rb:260:in `_extract_method_values'
  jbuilder (2.5.0) lib/jbuilder.rb:219:in `extract!'
  curation_concerns (1.6.2) app/views/curation_concerns/file_sets/show.json.jbuilder:1:in `__hydra_dev_heliotrope_staging_shared_vendor_bundle_ruby_______gems_curation_concerns_______app_views_curation_concerns_file_sets_show_json_jbuilder___2034905076601711768_70305683846280'
  actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
```

**Comment by conorom** [comment]
Actually if you reload the page a second time it seems the change does stick. Still the above error shouldn't happen and the change should appear immediately.
